version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_password
      - db_name
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_app

  web:
    image: moumou200/express-app-sample:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    secrets:
      - db_host
      - db_user
      - db_password
      - db_name
    environment:
      DB_HOST_FILE: /run/secrets/db_host
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME_FILE: /run/secrets/db_name
    depends_on:
      - db
    networks:
      - mysql_app

secrets:
  db_host:
    file: ./secrets/db_host.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt

volumes:
  db_data:

networks:
  mysql_app: 
    driver: overlay
